// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	kredivo "github.com/Bhinneka/kredivo-go"
	mock "github.com/stretchr/testify/mock"
)

// KredivoService is an autogenerated mock type for the KredivoService type
type KredivoService struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: _a0
func (_m *KredivoService) Cancel(_a0 *kredivo.CancelRequest) kredivo.ServiceResult {
	ret := _m.Called(_a0)

	var r0 kredivo.ServiceResult
	if rf, ok := ret.Get(0).(func(*kredivo.CancelRequest) kredivo.ServiceResult); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(kredivo.ServiceResult)
	}

	return r0
}

// Checkout provides a mock function with given fields: _a0
func (_m *KredivoService) Checkout(_a0 *kredivo.Order) kredivo.ServiceResult {
	ret := _m.Called(_a0)

	var r0 kredivo.ServiceResult
	if rf, ok := ret.Get(0).(func(*kredivo.Order) kredivo.ServiceResult); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(kredivo.ServiceResult)
	}

	return r0
}

// Confirm provides a mock function with given fields: _a0
func (_m *KredivoService) Confirm(_a0 *kredivo.ConfirmRequest) kredivo.ServiceResult {
	ret := _m.Called(_a0)

	var r0 kredivo.ServiceResult
	if rf, ok := ret.Get(0).(func(*kredivo.ConfirmRequest) kredivo.ServiceResult); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(kredivo.ServiceResult)
	}

	return r0
}

// GetPayments provides a mock function with given fields: _a0
func (_m *KredivoService) GetPayments(_a0 *kredivo.PaymentRequest) kredivo.ServiceResult {
	ret := _m.Called(_a0)

	var r0 kredivo.ServiceResult
	if rf, ok := ret.Get(0).(func(*kredivo.PaymentRequest) kredivo.ServiceResult); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(kredivo.ServiceResult)
	}

	return r0
}

// PartialCancel provides a mock function with given fields: _a0
func (_m *KredivoService) PartialCancel(_a0 *kredivo.PartialCancelRequest) kredivo.ServiceResult {
	ret := _m.Called(_a0)

	var r0 kredivo.ServiceResult
	if rf, ok := ret.Get(0).(func(*kredivo.PartialCancelRequest) kredivo.ServiceResult); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(kredivo.ServiceResult)
	}

	return r0
}

// TransactionStatus provides a mock function with given fields: _a0
func (_m *KredivoService) TransactionStatus(_a0 *kredivo.TransactionStatusRequest) kredivo.ServiceResult {
	ret := _m.Called(_a0)

	var r0 kredivo.ServiceResult
	if rf, ok := ret.Get(0).(func(*kredivo.TransactionStatusRequest) kredivo.ServiceResult); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(kredivo.ServiceResult)
	}

	return r0
}
